name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip' # built-in caching for pip

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Inject Version
      shell: pwsh
      run: |
        $version = "${{ github.ref_name }}"
        python scripts/inject_version.py $version

    - name: Build executable
      run: python build_exe.py

    - name: Bundle release
      run: python bundle_release.py

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/IcarusSentinel.exe
          IcarusSentinel.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
